<?php echo $this->partial('admin/sidebar.phtml', array('selected' => 'settings', 'item' => 'carburant')); ?>

<div id="content">
    <div class="left">
        <?php echo $this->partial('admin/items_list.phtml', array('list' => $this->list, 'controller' => 'carburant', 'action' => 'edit','id' => $this->id, 'fields' => array('CarburantID', 'CarburantName'))) ?>
    </div>
    
    <div class="right">
        
    </div>
</div>