<?php echo $this->partial('admin/sidebar.phtml', array('selected' => 'assurances', 'item' => 'garantie')); ?>

<div id="content">
    <div class="left">
        <?php echo $this->partial('admin/items_list.phtml', array('list' => $this->list, 'controller' => 'garantie', 'action' => 'edit','id' => $this->id, 'fields' => array('GarantieID', 'GarantieName'))) ?>
    </div>
    
    <div class="right">
        <h3 class="pagetitle icon property"><?php echo $this->translate('title.garantie'); ?></h3>
        <div class="form">
            <?php
                $this->garantieForm->setAction($this->url());
                echo $this->garantieForm;
            ?>
        </div>
    </div>
</div>