<?php if ($this->pageCount > 1): ?>
    <ul class="paginationControl">
       
        <?php if (isset($this->previous)): ?>

            <!-- Previous page link -->
            <li class="page page-previous">
                <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
                    &laquo; 
                </a>
            </li>
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
        
                <li class="page">
                    <a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
                </li>
            <?php else: ?>

                <li class="page current"><?php echo $page; ?></li>                    
            <?php endif; ?>
        <?php endforeach; ?>

        <?php if (isset($this->next)): ?>
            <!-- Next page link -->
            <li class="page page-next">
                <a href="<?php echo $this->url(array('page' => $this->next)); ?>">
                    &raquo;
                </a>
            </li>
        <?php endif; ?>
    </ul>
<?php endif; ?>