<div class="todo-list">
    <h1>TODO List</h1>

    <h2>Filters - ADMIN</h2>
    <ul>
        <li>Vehicule</li>
        <li>Tarification</li>
        <li>Assureur</li>
        <li>Souscripteur</li>
        <li>Package</li>
        <li>Attestation</li>
    </ul>

    <h2>Filters - Manager</h2>
    <ul>
        <li class="done">Tarification</li>
        <li class="done">Souscripteur</li>
        <li>Package (En cours ...)</li>
        <li>Attestation</li>
    </ul>

    <h2>Autre</h2>
    <ul>
        <li class="done">Gérer les garanties de chaque package (Admin)</li>
        <li class="done">Authefication séparer (Admin/manager)</li>
        <li class="done">Chaque assureur peut choisir une garantie</li>
        <li class="done">Change quelques champs "tarification" en textarea</li>
        <li class="done">Ajouter le champs description des garanties</li>
        <li class="done">Ajouter les champs manquants pour les tarifications</li>
        <li class="done">Upload logo</li>
        <li>...</li>
    </ul>
</div>
