<?php echo $this->partial('admin/sidebar.phtml', array('selected' => 'assurances', 'item' => 'tarification')); ?>

<div id="content">
    <div class="left">
        <?php echo $this->partial('admin/items_list.phtml', array('list' => $this->list, 'controller' => 'tarification', 'action' => 'edit','id' => $this->id, 'fields' => array('TarificationID', 'Prime'))) ?>
    </div>
    
    <div class="right">
        <h3 class="pagetitle icon property"><?php echo $this->translate('title.tarification'); ?></h3>
        <div class="form">
            <?php
                $this->tarificationForm->setAction($this->url());
                echo $this->tarificationForm;
            ?>
        </div>
    </div>
</div>