<?php echo $this->partial('admin/sidebar.phtml', array('selected' => 'settings', 'item' => 'marque')); ?>

<div id="content">
    <div class="left">
        <?php echo $this->partial('admin/items_list.phtml', array('list' => $this->list, 'controller' => 'marque', 'action' => 'edit','id' => $this->id, 'fields' => array('MarqueID', 'MarqueName'))) ?>
    </div>
    
    <div class="right">
        <h3 class="pagetitle icon property"><?php echo $this->translate('title.brand'); ?></h3>
        <div class="form">
            <?php
                $this->marqueForm->setAction($this->url());
                echo $this->marqueForm;
            ?>
        </div>
    </div>
</div>