<?php echo $this->partial('admin/sidebar.phtml', array('selected' => 'settings', 'item' => 'puissance')); ?>

<div id="content">
    <div class="left">
        <?php echo $this->partial('admin/items_list.phtml', array('list' => $this->list, 'controller' => 'puissance', 'action' => 'edit','id' => $this->id, 'fields' => array('PuissanceID', 'PuissanceNbChevDe', 'PuissanceNbChevA'))) ?>
    </div>
    
    <div class="right">
        
    </div>
</div>