<?php echo $this->partial('admin/sidebar.phtml', array('selected' => 'settings', 'item' => 'assureur')); ?>

<div id="content">
    <div class="left">
        <?php echo $this->partial('admin/items_list.phtml', array('list' => $this->list, 'controller' => 'assureur', 'action' => 'edit','id' => $this->id, 'fields' => array('AssureurID', 'AssureurName'))) ?>
    </div>
    
    <div class="right">
        <h3 class="pagetitle icon property"><?php echo $this->translate('title.insurance'); ?></h3>
        <div class="form">
            <?php
                $this->assureurForm->setAction($this->url());
                echo $this->assureurForm;
            ?>
        </div>
    </div>
</div>