<?php echo $this->partial('admin/sidebar.phtml', array('selected' => 'assurances', 'item' => 'attestation')); ?>

<div id="content">
    <div class="left">
        <?php echo $this->partial('admin/items_list.phtml', array('list' => $this->list, 'controller' => 'attestation', 'action' => 'edit','id' => $this->id, 'fields' => array('AttestationID', 'AttestationID'))) ?>
    </div>
    
    <div class="right">
        
    </div>
</div>