<?php echo $this->partial('admin/sidebar.phtml', array('selected' => 'settings', 'item' => 'cylindre')); ?>

<div id="content">
    <div class="left">
        <?php echo $this->partial('admin/items_list.phtml', array('list' => $this->list, 'controller' => 'cylindre', 'action' => 'edit','fields' => array('CylindreID', 'CylindreName'))) ?>
    </div>
    
    <div class="right">
        
    </div>
</div>