<div id="content">
    <h1>Tableau de bord</h1>

    <div class="dashboard-column-left">
        <h2>Les derniers inscrits</h2>
        <table class="list">
            <tr>
                <th>ID</th>
                <th>Nom et prénom</th>
                <th>Date d'inscription</th>
                <th>Type d'assurance</th>
            </tr>

            <tr class="even">
                <td>5</td>
                <td>LAAMRANI Younes</td>
                <td>05/01/2012</td>
                <td>Auto</td>
            </tr>
            <tr class="odd">
                <td>4</td>
                <td>SAADI Adam</td>
                <td>04/01/2012</td>
                <td>Moto</td>
            </tr>
            <tr class="even">
                <td>3</td>
                <td>SABIL Imane</td>
                <td>03/01/2012</td>
                <td>Auto</td>
            </tr>
            <tr class="odd">
                <td>2</td>
                <td>ROCHDI Ibrahim</td>
                <td>01/01/2012</td>
                <td>Auto</td>
            </tr>
            <tr class="even">
                <td>1</td>
                <td>AIT BELLA Hassan</td>
                <td>01/01/2012</td>
                <td>Moto</td>
            </tr>
        </table>
        <p><a href="#">Voir plus</a></p>

        <h2>Les derniers inscrits</h2>
        <table class="list">
            <tr>
                <th>ID</th>
                <th>Nom et prénom</th>
                <th>Date d'inscription</th>
                <th>Type d'assurance</th>
            </tr>

            <tr class="even">
                <td>5</td>
                <td>LAAMRANI Younes</td>
                <td>05/01/2012</td>
                <td>Auto</td>
            </tr>
            <tr class="odd">
                <td>4</td>
                <td>SAADI Adam</td>
                <td>04/01/2012</td>
                <td>Moto</td>
            </tr>
            <tr class="even">
                <td>3</td>
                <td>SABIL Imane</td>
                <td>03/01/2012</td>
                <td>Auto</td>
            </tr>
            <tr class="odd">
                <td>2</td>
                <td>ROCHDI Ibrahim</td>
                <td>01/01/2012</td>
                <td>Auto</td>
            </tr>
            <tr class="even">
                <td>1</td>
                <td>AIT BELLA Hassan</td>
                <td>01/01/2012</td>
                <td>Moto</td>
            </tr>
        </table>
        <p><a href="#">Voir plus</a></p>        
    </div>   

    <div class="dashboard-column-right">
        <h2>Les dernièrs paiements</h2>
        <table class="list">
            <tr>
                <th>ID</th>
                <th>Nom et prénom</th>
                <th>Date de paiement</th>
                <th>Package</th>
                <th>Montant</th>
            </tr>

            <tr class="even">
                <td>5</td>
                <td>LAAMRANI Younes</td>
                <td>05/01/2012</td>
                <td>Auto</td>
                <td>Auto</td>
            </tr>
            <tr class="odd">
                <td>4</td>
                <td>SAADI Adam</td>
                <td>04/01/2012</td>
                <td>Moto</td>
                <td>Moto</td>
            </tr>
            <tr class="even">
                <td>3</td>
                <td>SABIL Imane</td>
                <td>03/01/2012</td>
                <td>Auto</td>
                <td>Auto</td>
            </tr>
            <tr class="odd">
                <td>2</td>
                <td>ROCHDI Ibrahim</td>
                <td>01/01/2012</td>
                <td>Auto</td>
                <td>Auto</td>
            </tr>
            <tr class="even">
                <td>1</td>
                <td>AIT BELLA Hassan</td>
                <td>01/01/2012</td>
                <td>Moto</td>
                <td>Moto</td>
            </tr>
        </table>
        <p><a href="#">Voir plus</a></p>
        
        <h2>Les dernièrs paiements</h2>
        <table class="list">
            <tr>
                <th>ID</th>
                <th>Nom et prénom</th>
                <th>Date de paiement</th>
                <th>Package</th>
                <th>Montant</th>
            </tr>

            <tr class="even">
                <td>5</td>
                <td>LAAMRANI Younes</td>
                <td>05/01/2012</td>
                <td>Auto</td>
                <td>Auto</td>
            </tr>
            <tr class="odd">
                <td>4</td>
                <td>SAADI Adam</td>
                <td>04/01/2012</td>
                <td>Moto</td>
                <td>Moto</td>
            </tr>
            <tr class="even">
                <td>3</td>
                <td>SABIL Imane</td>
                <td>03/01/2012</td>
                <td>Auto</td>
                <td>Auto</td>
            </tr>
            <tr class="odd">
                <td>2</td>
                <td>ROCHDI Ibrahim</td>
                <td>01/01/2012</td>
                <td>Auto</td>
                <td>Auto</td>
            </tr>
            <tr class="even">
                <td>1</td>
                <td>AIT BELLA Hassan</td>
                <td>01/01/2012</td>
                <td>Moto</td>
                <td>Moto</td>
            </tr>
        </table>
        <p><a href="#">Voir plus</a></p>            
    </div>     
</div>