<div id="content">
    <?php echo $this->partial('elements/_tabs.phtml', array('SubMenuHome' => true, 'type' => 'auto')); ?>
        <h2>Les derniers inscrits</h2>
        <table class="list">
            <tr>
                <th>ID</th>
                <th>Nom et prénom</th>
                <th>Date d'inscription</th>
            </tr>

            <tr class="even">
                <td>5</td>
                <td>LAAMRANI Younes</td>
                <td>05/01/2012</td>
            </tr>
            <tr class="odd">
                <td>4</td>
                <td>SAADI Adam</td>
                <td>04/01/2012</td>
            </tr>
            <tr class="even">
                <td>3</td>
                <td>SABIL Imane</td>
                <td>03/01/2012</td>
            </tr>
            <tr class="odd">
                <td>2</td>
                <td>ROCHDI Ibrahim</td>
                <td>01/01/2012</td>
            </tr>
            <tr class="even">
                <td>1</td>
                <td>AIT BELLA Hassan</td>
                <td>01/01/2012</td>
            </tr>
        </table>
        <p><a href="#">Voir plus</a></p>
</div>